### ISSUE TITLE
Can't compile the code

### ISSUE THREAD

**Issue by suyashcjoshi** [hhexiy/pungen#2]
I tried the steps but couldn't compile the code the pun generator file is missing. In the paper, you have linked this for the code but the link is also broken : https://worksheets.codalab.org/worksheets/0x5a7d0fe35b144ad68998d74891a31ed6%20

Please help, really love to play with this.

**Comment by hhexiy** [comment]
Hi, the codalab link is this: https://worksheets.codalab.org/worksheets/0x5a7d0fe35b144ad68998d74891a31ed6 (not sure why the original one has an extra %...).

**Comment by suyashcjoshi** [comment]
thanks, let me look at this, btw just sent an email to your Stanford email address :)
